package com.GRP.Group5.RoadTripApp.Activities.Adapters;

import android.content.Context;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.TextView;

import com.GRP.Group5.RoadTripApp.R;
import com.GRP.Group5.RoadTripApp.Scheduling.SchedulablePlace;
import com.GRP.Group5.RoadTripApp.utils.Plan;
import com.GRP.Group5.RoadTripApp.utils.Route;

import java.util.List;

class PlanRemovalListAdapter extends ArrayAdapter<SchedulablePlace> {

    List<SchedulablePlace> places;
    Route route;
    SchedulablePlace currentPlace;

    /**
     * Init for the adapter
     * @param context
     * @param resource
     * @param plan
     * @param route
     * @param place
     */
    public PlanRemovalListAdapter(@NonNull Context context, int resource, Plan plan, Route route, SchedulablePlace place) {
        super(context, resource);

        this.places = plan.getPlaces();
        this.route = route;
        this.currentPlace = place;
    }

    /**
     * Returns the number of places within the list
     * @return
     */
    @Override
    public int getCount() {
        return this.places.size();
    }

    /**
     * Gets the SchedulablePlace at current position
     * @param position
     * @return
     */
    @Nullable
    @Override
    public SchedulablePlace getItem(int position) {
        return this.places.get(position);
    }

    /**
     * sets the contents to empty
     */
    @Override
    public void clear() {
        this.places.clear();
        super.clear();
    }

    /**
     * removes the object from the adapter
     * @param object
     */
    @Override
    public void remove(@Nullable SchedulablePlace object) {
        this.places.remove(object);
        this.route.removeSubLocation(this.currentPlace, object);
        super.remove(object);
    }

    /**
     * Gets the inflated view generated by this adapter at the given position
     * @param position
     * @param convertView
     * @param parent
     * @return
     */
    @NonNull
    @Override
    public View getView(final int position, @Nullable View convertView, @NonNull ViewGroup parent) {
        //Inflate the row
        LayoutInflater inflater = (LayoutInflater) this.getContext().getSystemService(Context.LAYOUT_INFLATER_SERVICE);
        View row = inflater.inflate(R.layout.remove_place_layout_comp, parent, false);

        //Views within the row
        TextView text = row.findViewById(R.id.removeText);
        Button removeButton = row.findViewById(R.id.removePlaceButton);

        //sets up the views with the appropiate data
        final SchedulablePlace place = this.getItem(position);

        text.setText(place.getName());

        removeButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                remove(place);
            }
        });

        return row;
    }
}
